### ISSUE TITLE
The annotations of AFLW dataset you provided does not contain 21 landmark points? Why is that?

### ISSUE THREAD

**Issue by Edwardmark** [D-X-Y/landmark-detection#24]

**Comment by D-X-Y** [comment]
I use 19 points without key-points for ear points. I simply use the annotation from previous papers http://mmlab.ie.cuhk.edu.hk/projects/compositional.html, and follow their setting.

**Comment by Edwardmark** [comment]
@D-X-Y Thank you man. I understand.
