### ISSUE TITLE
Questions about  'Evaluate on 300-W or AFLW'

### ISSUE THREAD

**Issue by bluesliuf** [D-X-Y/landmark-detection#25]
I recently read your paper SAN. Thank you very much for your open source code for everyone to learn. I hope that you can answer some of my questions in your spare time. I use your test script
‘’bash scripts/300W/300W-EVAL.sh 0,1
bash scripts/AFLW/AFLW_CYCLE_128.FULL-EVAL.sh 0,1‘’ has generated some .pth.tar files. 
I want to know what information these files hold and what they do. 
Addtionally, I want to know if there is a way to verify the images in bulk and save the visualization results (with landmark points). 
Thanks!

**Comment by D-X-Y** [comment]
Hi, the evaluation script will test one image and draw detected landmarks on this image as `https://github.com/D-X-Y/landmark-detection/blob/master/SAN/san_eval.py#L73`.
Would you mind to show me the name of those pth files?

**Comment by bluesliuf** [comment]
Thank you for your respond!
I have no problem about the test single image. 


My problem is that when I test on the 300-W and AFLW datasets, I will generate some .pth.tars files. I want to know what they save and what they can do,which can be seen in the attached images.

Other than that, I want to know if you have tried to test multiple images at the same time and save the visualization results with predicted landmarks.


-----------------------------------------------------------------------------------------------------
我对测试单张图片没有问题。
我的问题是在300-W和AFLW数据集上测试时，会生成一些.pth.tars文件，我想知道它们保存了什么，有什么作用，这些可以在附件图片中看见。
除此之外，我想知道您有没有试过同时测试多张图片并且保存可视化结果（包含预测关键点）。





------------------ 原始邮件 ------------------
发件人: "D-X-Y"<notifications@github.com>;
发送时间: 2019年7月1日(星期一) 上午9:06
收件人: "D-X-Y/landmark-detection"<landmark-detection@noreply.github.com>;
抄送: "平行线上的交点"<983854584@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [D-X-Y/landmark-detection] Questions about  'Evaluate on 300-W orAFLW' (#25)




Hi, the evaluation script will test one image and draw detected landmarks on this image as https://github.com/D-X-Y/landmark-detection/blob/master/SAN/san_eval.py#L73.
 Would you mind to show me the name of those pth files?

**Comment by D-X-Y** [comment]
In our internal codes, we visualize the predictions of all images for every epoch.

When testing, my code will save one result pth file for each test dataset. This pth file contains all the predictions and ground truth information (see details in https://github.com/D-X-Y/landmark-detection/blob/master/SAN/lib/san_vision/evaluation_util.py#L39 and https://github.com/D-X-Y/landmark-detection/blob/master/SAN/lib/procedure/evaluate_detector.py#L26).
