### ISSUE TITLE
Can't load the pre-trained model

### ISSUE THREAD

**Issue by xfj81525** [D-X-Y/landmark-detection#27]
Hi D-X-Y, I  downloaded the pre-trained model vgg16-397923af.pth and assign it as the model parameter when running eval.py, but it failed at param = snapshot['args'], reporting KeyError: 'args'.  so I retrain the detector as the doc describes , this error disappears, though the retrained detector looks not as good as your demo  
so please give me some help.  why can't the pre-trained model work well? the retrained model works not as good as your demo with the totally same code

**Comment by D-X-Y** [comment]
I will have a look at this problem. Please give me some time. Best RegardsXuanyi Dong-------- 原始邮件 --------主题：[D-X-Y/landmark-detection] Can't load the pre-trained model (#27)发件人：xfj81525 收件人：D-X-Y/landmark-detection 抄送：Subscribed Hi D-X-Y, I  downloaded the pre-trained model vgg16-397923af.pth and assign it as the model parameter when running eval.py, but it failed at param = snapshot['args'], reporting KeyError: 'args'.  so I retrain the detector as the doc describes , this error disappears, though the retrained detector looks not as good as your demo
so please give me some help.  why can't the pre-trained model work well? the retrained model works not as good as your demo with the totally same code

**Comment by xfj81525** [comment]
Great, thanks .

**Comment by D-X-Y** [comment]
Did you follow the evaluation README at https://github.com/D-X-Y/landmark-detection/tree/master/SAN#evaluation-on-the-single-image . I download my pre-trained model from https://drive.google.com/open?id=14f2lcJVF6E4kIICd8icUs8UuF3J0Mutd and evaluate use the following command, it works fine.
```
CUDA_VISIBLE_DEVICES=1 python san_eval.py --image ./cache_data/cache/test_1.jpg --model ./snapshots/SAN_300W_GTB_itn_cpm_3_50_sigma4_128x128x8/checkpoint_49.pth.tar --face 819.27 432.15 971.70 575.87 --save_path temp_1.png
```
