### ISSUE TITLE
the pretrained model is an invalid file

### ISSUE THREAD

**Issue by hsl20130659** [D-X-Y/landmark-detection#28]
TypeError: invalid file: PosixPath('checkpoint_49.pth.tar')

how to solve this problem?

**Comment by D-X-Y** [comment]
Would you mind to provide more information?

**Comment by hsl20130659** [comment]
snapshot = torch.load(snapshot,map_location='cpu')

I try load the pretrained model downloaded from the google cloud you provided ,but it does not work

**Comment by D-X-Y** [comment]
Would you mind to provide how do you place the snapshot file and provide a link to this code"snapshot = torch.load(snapshot,map_location='cpu')"?

**Comment by hsl20130659** [comment]
I run the san_eval.py on CPU,  I modified the 
snapshot = torch.load(snapshot) 
to  
snapshot = torch.load(snapshot,map_location='cpu')

**Comment by D-X-Y** [comment]
Did you exactly run "python san_eval.py --image ./cache_data/cache/test_1.jpg --model ./snapshots/SAN_300W_GTB_itn_cpm_3_50_sigma4_128x128x8/checkpoint_49.pth.tar --face 819.27 432.15 971.70 575.87 --save_path temp_1.png"?

**Comment by hsl20130659** [comment]
yes , I  put the args into the argparse.ArgumentParser

**Comment by D-X-Y** [comment]
I just add the CPU support for san_eval.py, and tried, but I did not find your issues.
Please make sure "checkpoint_49.pth.tar" is at snapshots/SAN_300W_GTB_itn_cpm_3_50_sigma4_128x128x8
![image](https://user-images.githubusercontent.com/9547057/61358350-b79ef500-a8ac-11e9-8917-8c38539bf750.png)

**Comment by hsl20130659** [comment]
I just replace the san_eval.py you modified ,it still does not work ,the problem is all the same

**Comment by D-X-Y** [comment]
Can you just share a screenshot of your error?

**Comment by hsl20130659** [comment]
![bug](https://user-images.githubusercontent.com/29247444/61362388-b376d580-a8b4-11e9-910a-5c74fe0c0a49.jpg)

**Comment by D-X-Y** [comment]
It might be caused by the PyThon version. I use Python 3.6 to save the model, but you are using Python 3.5. I also have this problem sometimes when load a model saved in different Python version. Would you mind to try Python 3.6?

**Comment by hsl20130659** [comment]
tks, I have run it on Python3.6 and it really works.
