### ISSUE TITLE
 [feature request] ICCV2019 paper 

### ISSUE THREAD

**Issue by PlumedSerpent** [D-X-Y/landmark-detection#32]
## Which project are you using?
TS3

## Issue description

Where can I find your ICCV2019 paper "Teacher Supervises Students How to Learn from Partially Labeled Images for Facial Landmark Detection" for now?
Can you provide a pdf copy?Thanks.

**Comment by D-X-Y** [comment]
@PlumedSerpent  I just uploaded it to arXiv.
It should be available tomorrow, and I will share the link here ASAP.

**Comment by PlumedSerpent** [comment]
@D-X-Y Thanks for your sharing. I'll close this issue.

**Comment by D-X-Y** [comment]
@PlumedSerpent Please find the PDF file in https://arxiv.org/abs/1908.02116

**Comment by PlumedSerpent** [comment]
@D-X-Y OK，I find it, thank you.
