### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by xubin19939** [D-X-Y/landmark-detection#34]
TS3 论文中没找到相关的速度性能，请问您训练的模型大小和在cpu 和 gpu下大概跑多少ms

**Comment by D-X-Y** [comment]
Sorry for the late reply. I'm a little bit busy this week, and will test it once I'm free.

**Comment by D-X-Y** [comment]
Please check the updated README: https://github.com/D-X-Y/landmark-detection/tree/master/TS3#model-configs . For the inference speed, different hardware will result in a different ms, you could run the test.py (with slight modification) to test on your preferred devices.
