### ISSUE TITLE
my own training dataset

### ISSUE THREAD

**Issue by lfxx** [D-X-Y/landmark-detection#36]
Thanks for your excellent work! i'd like to know how to make my own dataset to train a customed SAN network?just follow the 300W or aflw format?

**Comment by D-X-Y** [comment]
Thanks for your interest!
We generate several list files for each dataset (e.g., 300W in https://github.com/D-X-Y/landmark-detection/blob/master/SAN/cache_data/generate_300W.py#L106), each row contains three items, image-path / annotation-path / face-bounding-box-locations. You can refer to these two files to generate your own datasets (300W in https://github.com/D-X-Y/landmark-detection/blob/master/SAN/cache_data/generate_300W.py and https://github.com/D-X-Y/landmark-detection/blob/master/SAN/cache_data/aflw_from_mat.py

**Comment by lfxx** [comment]
Ok,thanks.but here is another two question:
1.Your style dataset have origin/gray/light/sketch four style,must i make four style datasets too?
2.Your style dataset have DET and GTB two style,need i make this too?
@D-X-Y

**Comment by D-X-Y** [comment]
1, You could use my style dataset to pre-train ResNet-152 so as to generate style-discriminative features. So no need to make four style datasets for your own dataset.

2, DET and GTB are two kinds of face bounding boxes provided by 300-W. You can use your face bounding boxes for your dataset.
