### ISSUE TITLE
Some questions after running 300W_Cluster.sh

### ISSUE THREAD

**Issue by lfxx** [D-X-Y/landmark-detection#38]
Hi,i have finished to run 300W_Cluster.sh on your style datasets,and it works well.But the cluster.lst seems a little strange,here is my txt log file:
[cluster_seed_1986_22-Aug-at-07-51-49.txt](https://github.com/D-X-Y/landmark-detection/files/3528970/cluster_seed_1986_22-Aug-at-07-51-49.txt)
I have three questions:
1.At the line 174,cluster-00-03.lst is extremely small since it has only 44 pictures in it,is that normal?
2.From your reply on other issue,when use those *.lst files to train network,which two files are needed for training cycleGAN?in your paper,a words saying:regard the group with the **maximum element** and the group with **the minimum** as two different style sets by default. These two different groups are then used to train style-unified face generation module.But from other issues,you said that largest two not (max and min) files are needed,so,which is True?
3.Is your network supports customed num landmark training,such as 106,108,even 1000 landmarks?whether just modify the num_pts value can make this?Maybe needs to modify the normalization method which is defined as  calculating the distance between the 37-th and the 46-th points?
Thanks!@D-X-Y

**Comment by D-X-Y** [comment]
1. It really depends on the datasets, if cluster-00-03.lst  only has 44 images, I would prefer to use cluster-01-03.lst and cluster-02-03.lst to train cyclegan.

2. In our paper, I remember we use the largest and the smallest one, which is tuned based on some empirical results. In your case, I would prefer to use cluster-01-03.lst and cluster-02-03.lst.

3. Modifying the num_pts is able to start training the model. The normalization method is different according to the dataset. We use the 37-th and the 46-th points for 300-W and sqrt(face-size) for AFLW. You can modify normalization to be able to correctly evaluate on your datasets.
