### ISSUE TITLE
 Using SAN project in a comparative review

### ISSUE THREAD

**Issue by Eman-salem** [D-X-Y/landmark-detection#40]
If you are submitting a feature request, please preface the title with [feature request].

If you are submitting a bug report, please fill in the following details.

## Which project are you using?
SAN or SBR or TS3 or others?

## Issue description

Provide a short description.

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by Eman-salem** [comment]
Hello , I am new in this field so my question could be naive. I need to use SAN project in a comparative review, Can i use the script of testing one image to evaluate on AFLW and 300w or other dataset  as my device having CPU only .

**Comment by D-X-Y** [comment]
Yes, you can follow two steps:
1, download trained model files following https://github.com/D-X-Y/landmark-detection/tree/master/SAN#evaluation-on-the-single-image
2, run this command:
```
python san_eval.py --image ./cache_data/cache/test_1.jpg --model ./snapshots/SAN_300W_GTB_itn_cpm_3_50_sigma4_128x128x8/checkpoint_49.pth.tar --face 819.27 432.15 971.70 575.87 --save_path temp_1.png --cpu
```
change `./cache_data/cache/test_1.jpg` to the target image and `819.27 432.15 971.70 575.87` to the face bounding box in your target image.
