### ISSUE TITLE
demo problem

### ISSUE THREAD

**Issue by flynnamy** [D-X-Y/landmark-detection#41]
I want to try SBR to vis demo-sbr.mp4.I execute scripts of demo_sbr.sh, but it has error about can not find eval-start-eval-00-01.pth.What is eval-start-eval-00-01.pth and how to get it?

**Comment by D-X-Y** [comment]
Which command do you use?
`eval-start-eval-00-01.pth` is the saved file after evaluating the SBR on the demo videos. Did you run evaluation?

**Comment by flynnamy** [comment]
@D-X-Y I only find that it has a script to eval an image of self.jpeg.It works.How to eval the SBR on video?Could you please share the scripts to do this?Thanks!

**Comment by D-X-Y** [comment]
Sorry for the late reply. I will have a look at this problem, thanks for your patience.

**Comment by D-X-Y** [comment]
You need to first train SBR on this demo video (https://github.com/D-X-Y/landmark-detection/blob/master/SBR/README.md#an-example-to-train-sbr-on-the-unlabeled-sequences) and then you will get this file (snapshots/CPM-SBR/metas/eval-start-eval-00-01.pth) for visualization.
