### ISSUE TITLE
[feature request] SBR on CPU?

### ISSUE THREAD

**Issue by ModarD** [D-X-Y/landmark-detection#42]
Is it possible to run SBR on CPU without CUDA? If yes, could you please give some info on how to achieve that?

I tried to replace cuda code but I am stuck with line 51 in eval.py
net = net.cuda()
not sure how to replace it!

**Comment by ModarD** [comment]
I just removed .cuda() from everywhere in eval.py! thanks

**Comment by D-X-Y** [comment]
Cool!
