### ISSUE TITLE
The checkpoint_49.pth.tar in SAN_300W_GTB_itn_cmp_3_50_sigma4_128_128_8 is broken

### ISSUE THREAD

**Issue by DanielYu7** [D-X-Y/landmark-detection#43]
If you are submitting a feature request, please preface the title with [feature request].

If you are submitting a bug report, please fill in the following details.

## Which project are you using?
SAN

## Issue description

The checkpoint_49.pth.tar in SAN_300W_GTB_itn_cmp_3_50_sigma4_128_128_8 is broken and can't be decompressed. Could you provide a new checkpoint-49.pth.tar in Baidu Yun? This will be a big help for me. Thank you very much!

**Comment by D-X-Y** [comment]
Sure, I'm uploading those snapshots to BAIDUYU.
What is your python version? I save the model in python 3.6, if you are using python 3.5 or python 2.7, there will be a problem.

**Comment by DanielYu7** [comment]
> Sure, I'm uploading those snapshots to BAIDUYU.
> What is your python version? I save the model in python 3.6, if you are using python 3.5 or python 2.7, there will be a problem.

I use python 3.6. But the key to my problem is that when I download the checkpoint_49.pth.tar from Google Drive, the file cannot be decompressed. 
![1567496276](https://user-images.githubusercontent.com/46912566/64153161-d1969600-ce60-11e9-8561-5a574a96a778.jpg)
I think the problem may be due to the loss of the file transfer process.

**Comment by D-X-Y** [comment]
I just update the README, please find the baidu pan link at https://github.com/D-X-Y/landmark-detection/tree/master/SAN#evaluation-on-the-single-image

**Comment by DanielYu7** [comment]
> I just update the README, please find the baidu pan link at https://github.com/D-X-Y/landmark-detection/tree/master/SAN#evaluation-on-the-single-image

I really appreciate your guidance and help very much.

**Comment by DanielYu7** [comment]
> I just update the README, please find the baidu pan link at https://github.com/D-X-Y/landmark-detection/tree/master/SAN#evaluation-on-the-single-image

I am very sorry to bother you again, but all the compressed files in the uploaded snapshots folder are still not open and cannot be decompressed. Maybe you should first decompress all the compressed files and then upload them all.

**Comment by D-X-Y** [comment]
Would you mind to provide commands that you run?

**Comment by DanielYu7** [comment]
> Would you mind to provide commands that you run?

Finally, I solve my problem, because I use the incorrect commands to run. Above all, thank you so much for your guidence.
