### ISSUE TITLE
PS method

### ISSUE THREAD

**Issue by fegnyujian** [D-X-Y/landmark-detection#44]
If you are submitting a feature request, please preface the title with [feature request].

If you are submitting a bug report, please fill in the following details.

## Which project are you using?
SAN

## Issue description

What is the specific ps method used to form the 300W-style and AFLW-style data sets proposed in the paper? If we want to use the style-aggregated face generation module method in the paper to synthesize our dataset, how do we form various styles?
Could you provide the PS method adopted in your paper? Thank you very much!

**Comment by D-X-Y** [comment]
Please refer to #7 . We are sorry that we lost the PS template that used for our -Style datasets.
