### ISSUE TITLE
SBR Base Detector?

### ISSUE THREAD

**Issue by ModarD** [D-X-Y/landmark-detection#46]
## Which project are you using?
SBR

Hello,
Thanks for the great code! unfortunately, it requires GPU processing which is not applicable in my case. However, It seems to me that the output of the base detector is sufficient for my goal, could you please give more details or reference some papers for the base detector? and does the base detector require GPU processing to run efficiently?

Thanks!

**Comment by D-X-Y** [comment]
"Stacked Hourglass Networks for Human Pose Estimation" and "convolutional pose machines" are two most popular base detectors and followed by many works. You can tune the configuration to allow them to run efficiently.
