### ISSUE TITLE
Hi！ some problems about data process

### ISSUE THREAD

**Issue by wqz960** [D-X-Y/landmark-detection#49]
It is about the project of SAN. If I want to train the network using my own dataset, how to use PS to process the three kinds of pictures. I have not used the PS before, can you tell me how to handle the pictures and the setting parameters of PS?(gray, sketch, light). Thank you!!!

**Comment by D-X-Y** [comment]
I'm not familiar with PS. My dataset is created by PS with the assistance of my friend. He first creates the template for gray, sketch, light, and then applies then to all images of the original 300W and AFLW. Unfortunately, we have lost the original template. Sorry for the inconvenience.

**Comment by wqz960** [comment]
@D-X-Y Thank you all the same for your quick respond! If you find the template some day, please contract me! Thank you! I am afraid that if you make the style dataset by my own template, the style-fusion module may not work!

**Comment by D-X-Y** [comment]
> @D-X-Y Thank you all the same for your quick respond! If you find the template some day, please contract me! Thank you! I am afraid that if you make the style dataset by my own template, the style-fusion module may not work!

Thanks for your reply. Changing the template may cause SAN ineffective. You could post some examples and we can discuss.
