### ISSUE TITLE
SAN 检测人脸关键点

### ISSUE THREAD

**Issue by wushunshun** [D-X-Y/landmark-detection#51]
请问，您的代码能否用来检测一张多个人脸的图片，并且输出一张带有关键点的图呢？

**Comment by D-X-Y** [comment]
这个算法需要预先给出face的bounding box框，如果你提供了该图片的每个人脸对应的bounding box，那么可以得到每一个脸的关键点。

**Comment by wushunshun** [comment]
哦哦，那也就是说，如果输入一张单张人脸的图片，也需要boundingbox了咯？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: D-X-Y <notifications@github.com&gt;
发送时间: 2019年11月18日 16:46
收件人: D-X-Y/landmark-detection <landmark-detection@noreply.github.com&gt;
抄送: wushunshun <1048276743@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[D-X-Y/landmark-detection] SAN 检测人脸关键点 (#51)




这个算法需要预先给出face的bounding box框，如果你提供了该图片的每个人脸对应的bounding box，那么可以得到每一个脸的关键点。

**Comment by D-X-Y** [comment]
是的，也需要bouding box，如果你知道这个图片就是单张人脸，可以提供(0,0,H,W)作为bounding box

**Comment by wushunshun** [comment]
哦哦好的谢谢呀



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: D-X-Y <notifications@github.com&gt;
发送时间: 2019年11月18日 18:20
收件人: D-X-Y/landmark-detection <landmark-detection@noreply.github.com&gt;
抄送: wushunshun <1048276743@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[D-X-Y/landmark-detection] SAN 检测人脸关键点 (#51)




是的，也需要bouding box，如果你知道这个图片就是单张人脸，可以提供(0,0,H,W)作为bounding box

**Comment by wushunshun** [comment]
那打扰您了，再问您一个问题，可以不训练，直接您预先训练的模型去检测单张图片吗？谢谢了！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: D-X-Y <notifications@github.com&gt;
发送时间: 2019年11月18日 18:20
收件人: D-X-Y/landmark-detection <landmark-detection@noreply.github.com&gt;
抄送: wushunshun <1048276743@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[D-X-Y/landmark-detection] SAN 检测人脸关键点 (#51)




是的，也需要bouding box，如果你知道这个图片就是单张人脸，可以提供(0,0,H,W)作为bounding box

**Comment by D-X-Y** [comment]
可以的，直接load pre-train model就行
