### ISSUE TITLE
Hit an AssertionError when running gen_mean_face.py in SAN

### ISSUE THREAD

**Issue by MANGA-1614** [D-X-Y/landmark-detection#52]
If you are submitting a feature request, please preface the title with [feature request].

If you are submitting a bug report, please fill in the following details.

## Which project are you using?
SAN or SBR or TS3 or others?
SAN

## Issue description
I ran gen_mean_face.py with the dataset folders in my home directory but I hit this error:
`AssertionError: /home/dxy/datasets/300W-Style/300W-Original/afw/4538917191_17.jpg is not a file`
I might have misinterpreted what /home/dxy is, but I am sure I placed the datasets folder in my home directory.

Google has not said anything either, only taking it as US dollar.

**Comment by D-X-Y** [comment]
/home/dxy is the home directory path on my local machine. I will check the path soon

**Comment by D-X-Y** [comment]
@MANGA-1614  Did you download the snapshot provided by me and then run `gen_mean_face.py`. If so some file paths in the snapshot is that on my machine, you can (1) generate those snapshots on your machine and then run `gen_mean_face.py` or (2) modify `gen_mean_face.py` to correct the path.

**Comment by MANGA-1614** [comment]
Hi,

Thank you for your response. I modified the snapshot files instead. I now
ran into a different problem.

`AssertionError: The path :
./snapshots/BASE-CLUSTER-300W_GTB-3/cluster-00-03.lst is not a file.`

I looked through your snapshot folder in Google Drive but couldn't find
this. Was I supposed to make this myself?

**Comment by D-X-Y** [comment]
@MANGA-1614 You can 
(1) generate by your own by running `bash scripts/300W/300W_Cluster.sh 0,1 GTB 3` as in https://github.com/D-X-Y/landmark-detection/tree/master/SAN#300-w
or (2) use the existing one from https://drive.google.com/open?id=1DtUg0LoZXNuDxeqRtcRxrA4tjrN9rpJa .
I prefer you generate it on your own as this step does not cost much time.

**Comment by MANGA-1614** [comment]
@D-X-Y/landmark-detection
<reply@reply.github.com>,

I do have that one, straight from Google Drive. I couldn't run it since it
was a shell script and most of my Python was done in Windows.

However, in gen_mean_face.py, it looks out for 2 lists: CLUSTER-300W_GTB-3
and BASE-CLUSTER-300W_GTB-{:d}.

`
save_path = osp.join('cache_data', 'cache', 'clusters',
'300W-{:}'.format(cluster_num), '300W-{:}-{:}.png'.format(i, cluster_num))

calculate_mean(['./snapshots/CLUSTER-300W_GTB-{:d}/cluster-{:02d}-{:02d}.lst'.format(cluster_num,
i, cluster_num)], 68, save_path)

    save_path = osp.join('cache_data', 'cache', 'clusters',
'300W-BASE-{:}'.format(cluster_num), '300W-BASE-{:}-{:}.png'.format(i,
cluster_num))

calculate_mean(['./snapshots/BASE-CLUSTER-300W_GTB-{:d}/cluster-{:02d}-{:02d}.lst'.format(cluster_num,
i, cluster_num)], 68, save_path)
`

I got through the first one, but not the second one.

I'm terribly sorry about my inquiries. I'm new to both Python and Computer
Vision.

**Comment by D-X-Y** [comment]
I see. The "BASE-C...." is generated by `scripts/300W/300W_Base_Cluster.sh`. You can try to modify the script to run on Windows.

**Comment by MANGA-1614** [comment]
Ah ok, I see. Sounds good. I'll try to edit that then.

Right now, I've decided to comment it out. I'll return it back if anything
happens.
