### ISSUE TITLE
Environment and Computer Specs Used During Training and Testing

### ISSUE THREAD

**Issue by MANGA-1614** [D-X-Y/landmark-detection#54]
Hello, 

Sorry to ask again, but I couldn't find it in your paper, but what were the specs of the computer used for your training and testing? I saw on the paper that you had 2 GPUs.

**Comment by D-X-Y** [comment]
For the checkpoints provided in this repo, I use two 1080Ti.

**Comment by MANGA-1614** [comment]
Thank you!

**Comment by D-X-Y** [comment]
You are welcome.
