### ISSUE TITLE
SAN init_path using

### ISSUE THREAD

**Issue by v-goncharenko** [D-X-Y/landmark-detection#55]
## Which project are you using?
SAN

## Issue description

I'm trying to evaluate your models through `san_eval.py` file and I'm converting `evaluate` function to kind of API endpoint to be able to use it as a client.

I wonder why do you use `sys.path` patching instead of simply importing modules in `from lib import models` fashion?
For me this is an issue cause it affects my runtime if I use your code.
Could you (or me in PR) fix imports to preserve `sys.path` untouched?

By the way I could provide PR for an API I've wrote if you are interested in it.

**Comment by D-X-Y** [comment]
Hi, it is because `from lib import models` require a python file in the same dir as lib.
Without `sys.path` it is fine in SAN. While my other projects use `sys.path`, so I'm used to using it.
You are welcome to create a PR for API. Thanks a lot for your effort.
