### ISSUE TITLE
Hi，some question about the style aggregated images?

### ISSUE THREAD

**Issue by wqz960** [D-X-Y/landmark-detection#61]
Hi！There are some problems about SAN.
In your paper, style diversity in face dataset will cause the accuracy loss in face landmarks detection, you use the style aggregated to ease this situation, If when we train the model, I use all face images including the synthetic face image made by PS, it is equivalent to doing data augmentation， doesn't this data augmentation technology also make face images of various styles learned by the network? How is this different from your style aggregated network？

**Comment by D-X-Y** [comment]
That is a good question. I did this ablation study two years ago. Training with PS-generated synthetic face images gets a slightly worse performance, but I forget the exact numbers.
These PS-generated synthetic face images are like some sparse points at the data space, which has limited numbers. While our GAN-generated images are infinite, and thus has more potential than it.
