### ISSUE TITLE
[QUESTION] How to use pre trained model and pth?

### ISSUE THREAD

**Issue by sevaraMS** [D-X-Y/landmark-detection#63]
I want to just see output result of 68 predicted points, When I tried visualize the 68 points,  using pre trained eval-epoch-049-050-02-03.pth it is give me mistake. FileNotFoundError: [Errno 2] No such file or directory: '/home/dxy/datasets/landmark-datasets/300W/helen/testset/3243018729_1.jpg'

**Comment by D-X-Y** [comment]
The pre-trained model is trained on my machine, where the data path is at "/home/dxy/datasets/landmark-datasets/" and it will be saved.
There are two options, 
- Using our pre-trained model to predict on your own images.
- Replace the file path to the path on your machine. (You need to modify the path at here: https://github.com/D-X-Y/landmark-detection/blob/master/SAN/lib/san_vision/evaluation_util.py#L36).

**Comment by sevaraMS** [comment]
THANK YOU
