### ISSUE TITLE
怎么用SBR提升我已经训练好的106关键点检测模型呢？

### ISSUE THREAD

**Issue by gjd2017** [D-X-Y/landmark-detection#66]
If you are submitting a feature request, please preface the title with [feature request].

If you are submitting a bug report, please fill in the following details.

## Which project are you using?
SAN or SBR or TS3 or others?

## Issue description

Provide a short description.

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by D-X-Y** [comment]
You can use your pre-trained landmark detection model as the initialization for SBR.
To optimize your model with SBR, you need (1) labeled training data (which could be the training data for your pre-training) and (2) unlabeled video data (you can collect them on your own). An example is at here: https://github.com/D-X-Y/landmark-detection/tree/master/SBR#improving-the-detector-by-sbr

Please feel free to re-open the issue if you have more questions.
