### ISSUE TITLE
How to train the network with the new dataset

### ISSUE THREAD

**Issue by zhouqianyu0918** [D-X-Y/landmark-detection#70]
Thank you for your work！
How do I get the bounding box if I use my own dataset

**Comment by QcQcM** [comment]
I think you can use the face detector to detect the face frame of each picture, and then generate the same training list as the author
I don’t know which project you are asking about. The above mentioned is for SAN

**Comment by D-X-Y** [comment]
Thanks, @QcQcM .

@zhouqianyu0918 For all algorithms in this repo, you need to either provide the bounding box data for your training face images or detect the facial bounding box on your own and provide.
 Here is a very short example code for generating the dataset file that could be used in SBR/SRT: https://github.com/D-X-Y/landmark-detection/blob/master/SRT/cache_data/GEN_demo.py#L52. Where you just need to replace "box" by your detected bounding box location.
