### ISSUE TITLE
Pretrained Model of SRT?

### ISSUE THREAD

**Issue by CodingMice** [D-X-Y/landmark-detection#71]
Is there any pretrained models of SRT? I am looking forward to test it.

**Comment by D-X-Y** [comment]
Yes, we have. I need some time to download them from the server and then upload to Google Drive.

**Comment by Tetomach** [comment]
I'm anxious to see how the increase in temporal precision impacts video data collected from mobile devices.
My work uses a landmark detection system to provide a framework for specific types of behavioral classification. 
Currently, I'm in the process of writing my dissertation, and I'd love to be able to include a comparison and future perspective using your model's localization.
I realize you're quite busy, so I definitely don't want to be a pest, but it would be excellent if you could find the time to upload these models!

**Comment by D-X-Y** [comment]
@Tetomach Thanks for your interest. I just uploaded some pre-trained models at here: https://drive.google.com/drive/folders/1uGRf74VecXwNzwMzxxlkVfvreIwGoOHa?usp=sharing

The models included the regression model pre-trained on 300-W, 300-W with (SBR augmented) 300VW, 300-W with (SBR augmented) VOX, 300-W with (SBR augmented) PanopticFace, and 300-W with (SRT augmented) PanopticFace.

Having fun!
