### ISSUE TITLE
How to divide 300VW-Dataset into 3 categories

### ISSUE THREAD

**Issue by QcQcM** [D-X-Y/landmark-detection#72]
## Which project are you using?
SBR

## Issue description

Hi，I have noticed in the paper of SBR 
"300-VW [30, 34, 6]. This video dataset contains 50 training videos with 95192 frames. The test set consists of
three categories with different levels. These three subsets (A, B and C) have 62135, 32805 and 26338 frames, respectively. C is the most challenging one." 
and in many articles about face landmark detection based on video,they have also mentioned the 3 categories of 300VW and done some comparison  separately in 3 scenarios.
But for  the 300VW data set I have downloaded, neither train/test set nor category-A/ category-B/category-C is divided.
So I wanna to ask whether the 3 categories have been divided before download, or you divide it according to the requirements of the official website? 
 (the official website link is https://ibug.doc.ic.ac.uk/resources/300-VW/)
I have tried to divide it by myself, but the test result of my model is weird. My model's performance is better in category C.

**I really hope to get your answer,because I don't have any classmates who do the same direction as me ,and there is very little information about this detail**

**Thx a lot!!!**

**Comment by D-X-Y** [comment]
Here is the video id for the three test category (1 for A, 2 for B, 2 for C): https://github.com/D-X-Y/landmark-detection/blob/master/SBR/cache_data/generate_300VW.py#L98
I found these ids somewhere three years ago, and forget the original sources. But I think you use re-use them safely.
