### ISSUE TITLE
Problem about training SBR with 300VW dataset

### ISSUE THREAD

**Issue by QcQcM** [D-X-Y/landmark-detection#77]
## Which project are you using?
SBR

## Issue description
Hi, I have replaced the vgg16 base detector in SBR with my own model, and I want to check if the  LK operation can improve my model's performance on 300-VW video dataset.
I generated the train lists of 300-VW follow the READ ME in cache_data.
![2020-11-25 15-03-05 的屏幕截图](https://user-images.githubusercontent.com/46199240/100193762-6175a380-2f2f-11eb-8807-5725b3e3b6ce.png)
According to my understanding, two types of training lists are generated for each video sample. The one ending in .none is not  annotated with the truth value of the key point, and the other opposite.
The content of the file is the same as the demo-sbr.lst used in the training example, so I only  change the parameters '--train_lists' during training to train my model+SBR with 300VW

`python lk_main.py --train_lists
./cache_data/lists/300VW/300VW.train.lst001
./cache_data/lists/300VW/300VW.train.lst002
./cache_data/lists/300VW/300VW.train.lst003
./cache_data/lists/300VW/300VW.train.lst004
./cache_data/lists/300VW/300VW.train.lst007
./cache_data/lists/300VW/300VW.train.lst009
./cache_data/lists/300VW/300VW.train.lst010
./cache_data/lists/300VW/300VW.train.lst011
./cache_data/lists/300VW/300VW.train.lst013
./cache_data/lists/300VW/300VW.train.lst015
./cache_data/lists/300VW/300VW.train.lst016
./cache_data/lists/300VW/300VW.train.lst017
./cache_data/lists/300VW/300VW.train.lst018
./cache_data/lists/300VW/300VW.train.lst019
./cache_data/lists/300VW/300VW.train.lst020
./cache_data/lists/300VW/300VW.train.lst022
./cache_data/lists/300VW/300VW.train.lst025
./cache_data/lists/300VW/300VW.train.lst027
./cache_data/lists/300VW/300VW.train.lst028
./cache_data/lists/300VW/300VW.train.lst029
./cache_data/lists/300VW/300VW.train.lst031
./cache_data/lists/300VW/300VW.train.lst033
./cache_data/lists/300VW/300VW.train.lst034
./cache_data/lists/300VW/300VW.train.lst035
./cache_data/lists/300VW/300VW.train.lst037
./cache_data/lists/300VW/300VW.train.lst039
./cache_data/lists/300VW/300VW.train.lst041
./cache_data/lists/300VW/300VW.train.lst043
./cache_data/lists/300VW/300VW.train.lst044
./cache_data/lists/300VW/300VW.train.lst046
./cache_data/lists/300VW/300VW.train.lst047
./cache_data/lists/300VW/300VW.train.lst048
./cache_data/lists/300VW/300VW.train.lst049
./cache_data/lists/300VW/300VW.train.lst053
./cache_data/lists/300VW/300VW.train.lst057
./cache_data/lists/300VW/300VW.train.lst059
./cache_data/lists/300VW/300VW.train.lst112
./cache_data/lists/300VW/300VW.train.lst113
./cache_data/lists/300VW/300VW.train.lst115
./cache_data/lists/300VW/300VW.train.lst119
./cache_data/lists/300VW/300VW.train.lst120
./cache_data/lists/300VW/300VW.train.lst123
./cache_data/lists/300VW/300VW.train.lst138
./cache_data/lists/300VW/300VW.train.lst143
./cache_data/lists/300VW/300VW.train.lst144
./cache_data/lists/300VW/300VW.train.lst160
./cache_data/lists/300VW/300VW.train.lst204
./cache_data/lists/300VW/300VW.train.lst205
./cache_data/lists/300VW/300VW.train.lst223
./cache_data/lists/300VW/300VW.train.lst225
--eval_ilists ./cache_data/lists/demo/demo-sbr.lst
--num_pts 69
--model_config ./configs/Detector.config
--opt_config ./configs/LK.SGD.config
--lk_config ./configs/mix.lk.config
--video_parser x-1-1
--save_path ./snapshots/CPM-SBR
--init_model ./snapshots/SAN_mobilenet_300W_GTB_itn_cpm_3_50_sigma4_128x128x8_new/checkpoint_99.pth.tar
--pre_crop_expand 0.2
--sigma 4
--batch_size 1
--crop_perturb_max 5
--scale_prob 1
--scale_min 1
--scale_max 1
--scale_eval 1
--heatmap_type gaussian
--print_freq 10`

The key points is basically accurate when test on demo with the original model, but after 10 rounds of training according to the above method, the positions of the key points are all messed up, and the error rate of the original model on 300VW has also increased may times.
Is the way I train wrong?

Looking forward to your reply, thank you for your continued help.:heart::heart::heart:

**Comment by Dian-Yi** [comment]
训练好的效果如何？keypoints会更稳定么？
