### ISSUE TITLE
SRT inference get wrong results

### ISSUE THREAD

**Issue by flynnamy** [D-X-Y/landmark-detection#81]
Hi, I execute this command:python exps/BASE-eval-image.py --image ./cache_data/cache/self.jpeg --face 250 150 900 1100 --model checkpoint-regression.pth,but get wrong landmark like followings pic. Any suggestions? @D-X-Y 
![image](https://user-images.githubusercontent.com/20398890/104434374-1e968a80-55c6-11eb-896f-751de52ecba2.png)

**Comment by AndriiHura** [comment]
I can't even run inference with this `--model checkpoint-regression.pth` checkpoint as I right away get a ` Missing key(s) in state_dict:` error.

**Comment by D-X-Y** [comment]
@AndriiHura Could you please show your step-by-step commands? The missing keys are due to the mismatch between DaraParallel Model and the original model

**Comment by flynnamy** [comment]
@D-X-Y Please see my results, Any suggestions?

**Comment by D-X-Y** [comment]
@flynnamy It was my fault that used an old eval file from SBR.. I just updated the codes, please have a try now. I tried it on my laptop and works fine.

**Comment by D-X-Y** [comment]
Please feel free to re-open this issue if you have another question.

**Comment by AndriiHura** [comment]
@D-X-Y Now it works great! Thanks a lot :)
