### ISSUE TITLE
SRT inference on video

### ISSUE THREAD

**Issue by zero0kiriyu** [D-X-Y/landmark-detection#85]
Hi, I am trying to use the SRT to get the landmark of the video. I have already finished the face detection, but I haven't found the script for evaluating the video. What do I have to do to get the video landmark?

**Comment by D-X-Y** [comment]
The current script is prepared for the existing datasets.
If you need to evaluate your video, you can:
(1) create a dataset file for your video (like this one https://github.com/D-X-Y/landmark-detection/blob/master/SRT/cache_data/GEN_300VW.py#L148)
(2) add the file path to the eval_ilists args (like this one https://github.com/D-X-Y/landmark-detection/blob/master/SRT/scripts/300VW/X-REG-300VW.sh#L32)

**Comment by zero0kiriyu** [comment]
I'm sorry, but it's a little hard for me to figure out which part is needed to predict the landmark of the video. It would be nice if you could provide a script like the BASE-eval-image.py that can be used to predict the landmark.
