### ISSUE TITLE
[Dataset issues] How to download "Synthetic-Face" dataset?

### ISSUE THREAD

**Issue by ZhenglinZhou** [D-X-Y/landmark-detection#86]
## Which project are you using?
SBR & SRT

## Issue description
Hi, Xuanyi. It's really an impressive work! Recently, I want to eval our ld detector on this "zero annotation error" dataset.  But no download link was found about it, which confused me a lot. I list some questions below:
1. Is it an open source dataset? 
 1) If  yes, how can I download it?
 2) If no, how can I reproduce it? And is there some introduction paper or blog?

Many thanks!

**Comment by D-X-Y** [comment]
Thanks for your interests! Unfortunately, it is an internal dataset at Facebook/Meta and can not be open-sourced.

A suggestion to reproduce that is to use some 3D geometry model to construct 3D face and project it to 2D to create such Synthetic dataset.

**Comment by ZhenglinZhou** [comment]
OK, thanks for your prompt reply!
